services:
  - type: web
    name: predovex-backend
    env: docker
    region: oregon
    plan: free
    dockerContext: .
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: predovex-postgres
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"

databases:
  - name: predovex-postgres
    plan: free
